name: TTL Verify Stable
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Topic produced by ttl-verify-generator
    defaultValue: ttl-verify-input
    required: true
  - name: output
    inputType: OutputTopic
    description: Topic for messages that passed the stable (no-TTL) deduper
    defaultValue: ttl-verify-stable-out
    required: true
dockerfile: build/dockerfile
runEntryPoint: main.py
defaultFile: main.py
